### ISSUE TITLE
Readme: add screenshot with where to find the "edit kernelspec" button.

### ISSUE THREAD

**Issue by Carreau** [deshaw/ksmm#25]
Also the current screenshot have typos, IPython is uppercase I.

**Comment by ericdatakelly** [comment]
I think the screenshot is done.  Are the typos fixed too?  If so, this issue could be closed.

**Comment by echarles** [comment]
I don't see typos on the new screenshots present on https://github.com/deshaw/ksmm/blob/main/README.md

If there are, we would. need to fix and release.
